apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpafordotnetsample
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: {{ .Values.targetCPUUtilizationPercentage }}