apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{.Values.appName}}
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP